// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SGD_C
NumericVector SGD_C(IntegerMatrix matrix, NumericVector result, NumericVector theta, float loss);
RcppExport SEXP _StatComp22004_SGD_C(SEXP matrixSEXP, SEXP resultSEXP, SEXP thetaSEXP, SEXP lossSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type result(resultSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< float >::type loss(lossSEXP);
    rcpp_result_gen = Rcpp::wrap(SGD_C(matrix, result, theta, loss));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StatComp22004_SGD_C", (DL_FUNC) &_StatComp22004_SGD_C, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_StatComp22004(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
